name = "Jet"
uuid = "ea576619-15d3-4675-b24c-7b7a8f11ced0"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"

[compat]
Crayons = "4.0"
DataStructures = "0.18"
JSON = "0.21"
ReplMaker = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
