name = "TLDR"
uuid = "ea576619-15d3-4675-b24c-7b7a8f11ced0"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com>"]
version = "0.2.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"

[compat]
Crayons = "4.0"
DataStructures = "0.18"
GitHub = "5"
JSON = "0.21"
ReplMaker = "0.2"
StringDistances = "0.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
